import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useContext, useEffect } from 'react'
import { useRouter } from 'next/router'
import Login from '@/Components/Login/login'
import { AuthContext } from '@/lib/Context'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Icon.png" />
      </Head>
      <div style={{display:"flex",alignItems:"center",justifyContent:"center",height:"100vh"}}>
        <Login/>
      </div>
    </>
  )
}
